"""
Django settings for gatinos project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", default="foo")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.environ.get("DEBUG", default=0))

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", default="localhost 127.0.0.1 [::1]").split(" ")


# Application definition

APPLICATION_TITLE = "Aplicacion para la Gestión de Colonias de Gatos"

INSTALLED_APPS = [
    'gatos',
    'registration',
    'utils',
    'plottings',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gatinos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "gatinos" / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'utils.context_processors.metadata',
                'utils.context_processors.anuncios',
            ],
        },
    },
]


FORM_RENDERER = "gatinos.forms.FormRenderer"


WSGI_APPLICATION = 'gatinos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get("SQL_ENGINE", "django.db.backends.sqlite3"),
        'NAME': os.environ.get("SQL_DATABASE", BASE_DIR / "db.sqlite3"),
        'USER': os.environ.get("SQL_USER", "user"),
        'PASSWORD': os.environ.get("SQL_PASSWORD", "password"),
        'HOST': os.environ.get("SQL_HOST", "localhost"),
        'PORT': os.environ.get("SQL_PORT", "port"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True

# Security

LOGIN_URL = "cuentas/login"

GROUPS_PERMISSIONS = {
        "cuidador": ["view_colonia",
                     "view_gato",
                     "view_foto",
                     "add_foto",
                     "add_informe",
                     "view_informe",
                     "view_enfermedad",
                     "alimentar_colonia",
                     "avistar_gato",
                     ],
        "veterinario": ["view_colonia",
                        "view_gato",
                        "change_gato",
                        "view_foto",
                        "add_foto",
                        "add_informe",
                        "view_informe",
                        "add_gato",
                        "view_enfermedad",
                        "add_enfermedad",
                        "change_enfermedad",
                        "delete_enfermedad",
                        "vacunar_gato",
                        ],
        "autoridad": ["view_colonia",
                      "change_colonia",
                      "view_gato",
                      "change_gato",
                      "add_gato",
                      "add_informe",
                      "view_informe",
                      "view_foto",
                      "add_foto",
                      "change_foto",
                      "capturar_gato",
                      "liberar_gato",
                      "view_enfermedad",
                      ],
        "visitante": ["view_colonia",
                      "view_gato",
                      "view_foto",
                      "view_informe",
                      "view_enfermedad",
                      ]
        }


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STORAGES = {
        "default": {
            "BACKEND": os.environ.get("STORAGES_BACKEND",
                                      default = "django.core.files.storage.FileSystemStorage"),
            },
        "staticfiles": {
            "BACKEND": os.environ.get("STATICFILES_STORAGES_BACKEND",
                                      default = "django.contrib.staticfiles.storage.StaticFilesStorage"),
            }
        }


STATIC_URL = os.environ.get("STATIC_URL", default="/static/")
STATIC_ROOT = os.environ.get("STATIC_ROOT", default="/var/www/gatinos/static/")


STATIC_ROOT = '/tmp/gatinos_static'

STATICFILES_DIRS = [
        BASE_DIR / "gatinos/static",
        ]

MEDIA_URL = os.environ.get("MEDIA_URL", default="media/")
MEDIA_ROOT = os.environ.get("MEDIA_ROOT", default="/var/www/gatinos/media/")

RELLENO_FOTO_URL = "fotos/relleno.svg"
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
