# Generated by Django 4.2.3 on 2024-07-03 16:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gatos.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Captura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(blank=True, default='', max_length=200)),
                ('fecha_captura', models.DateField(auto_now=True)),
                ('fecha_liberacion', models.DateField(default=None, null=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('esterilizacion', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, default='')),
            ],
            options={
                'permissions': [('capturar_gato', ''), ('liberar_gato', '')],
            },
        ),
        migrations.CreateModel(
            name='Colonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', max_length=200, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('periodo_activo', models.DurationField(default=datetime.timedelta(days=120))),
                ('descripcion', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('nombre_usuario', models.CharField(blank=True, default='', max_length=200)),
                ('id', models.UUIDField(default=gatos.utils.random_choice, editable=False, primary_key=True, serialize=False)),
                ('foto', models.ImageField(upload_to='fotos/%Y/%m/%d')),
                ('miniatura', models.ImageField(default='', upload_to='miniaturas/%Y/%m/%d')),
                ('exif', models.JSONField(default=dict)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fea', models.BooleanField(default=False)),
                ('colonia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='gatos.colonia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', max_length=200, unique=True)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('color', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=10)),
                ('esterilizacion', models.DateField(blank=True, null=True)),
                ('feo', models.BooleanField(default=False)),
                ('vecino', models.BooleanField(default=False)),
                ('nombre_vecino', models.CharField(blank=True, max_length=200)),
                ('fecha_alta', models.DateField(auto_now=True)),
                ('muerto', models.BooleanField(default=False)),
                ('muerto_fecha', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(default='LIBRE', max_length=200)),
                ('colonia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gatos', to='gatos.colonia')),
                ('retrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gatos.foto')),
            ],
        ),
        migrations.CreateModel(
            name='Vacunacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(blank=True, default='', max_length=200)),
                ('tipo', models.CharField(choices=[('DESPARASITADO', 'Desparasitado')], max_length=100)),
                ('efecto', models.DurationField()),
                ('captura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to='gatos.captura')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'vacunaciones',
                'permissions': [('vacunar_gato', '')],
            },
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(blank=True, default='', max_length=200)),
                ('fecha', models.DateField(auto_now=True)),
                ('titulo', models.CharField(max_length=250)),
                ('texto', models.TextField(blank=True, null=True)),
                ('colonia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='gatos.colonia')),
                ('gatos', models.ManyToManyField(related_name='informes', to='gatos.gato')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='foto',
            name='gatos',
            field=models.ManyToManyField(blank=True, related_name='fotos', to='gatos.gato'),
        ),
        migrations.AddField(
            model_name='foto',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(blank=True, default='', max_length=200)),
                ('diagnostico', models.CharField(max_length=200)),
                ('fecha_diagnostico', models.DateField(auto_now=True)),
                ('fecha_curacion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('gato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfermedades', to='gatos.gato')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'enfermedades',
            },
        ),
        migrations.AddField(
            model_name='captura',
            name='gato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capturas', to='gatos.gato'),
        ),
        migrations.AddField(
            model_name='captura',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Avistamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(blank=True, default='', max_length=200)),
                ('fecha', models.DateField(auto_now=True)),
                ('colonia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avistamientos', to='gatos.colonia')),
                ('gato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avistamientos', to='gatos.gato')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('avistar_gato', '')],
            },
        ),
        migrations.CreateModel(
            name='AsignacionComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('colonia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comidas', to='gatos.colonia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
