# Generated by Django 5.0.1 on 2024-05-06 05:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gato',
            name='id',
        ),
        migrations.AddField(
            model_name='gato',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
