# Generated by Django 4.2.3 on 2024-07-03 16:24

from django.db import migrations, models
import gatos.utils


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='id',
            field=models.CharField(default=gatos.utils.random_choice, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
