# Generated by Django 4.2.3 on 2024-07-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0002_alter_foto_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField(blank=True, null=True)),
                ('urgencia', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], default='MEDIO', max_length=20)),
            ],
        ),
    ]
