# Generated by Django 5.0.1 on 2024-05-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0002_remove_gato_id_gato_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gato',
            name='uuid',
        ),
        migrations.AddField(
            model_name='colonia',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='gato',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='gato',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='colonia',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
