# Generated by Django 5.0.1 on 2024-05-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0003_remove_gato_uuid_colonia_slug_gato_id_gato_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gato',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
