# Generated by Django 4.2.3 on 2024-07-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0003_anuncio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='hora_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
