# Generated by Django 5.0.1 on 2024-05-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0004_alter_colonia_id_alter_gato_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gato',
            name='descripcion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
