# Generated by Django 4.2.3 on 2024-07-04 05:57

from django.db import migrations, models
import gatos.models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0004_alter_anuncio_hora_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(upload_to=gatos.models.foto_upload_to),
        ),
    ]
