# Generated by Django 4.2.3 on 2024-07-04 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0005_alter_foto_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacioncomida',
            options={'permissions': [('alimentar_colonia', '')]},
        ),
    ]
