# Generated by Django 4.2.3 on 2024-05-21 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0005_gato_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gato',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='gato',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('colonia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatos.colonia')),
            ],
        ),
    ]
