# Generated by Django 4.2.3 on 2024-05-21 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0006_alter_gato_nombre_alter_gato_slug_fotos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fotos',
            new_name='Foto',
        ),
        migrations.AddField(
            model_name='gato',
            name='foto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gatos.foto'),
        ),
    ]
