# Generated by Django 4.2.3 on 2024-07-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0006_alter_asignacioncomida_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gato',
            name='marcado',
            field=models.BooleanField(default=False),
        ),
    ]
