# Generated by Django 4.2.3 on 2024-05-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0007_rename_fotos_foto_gato_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='descripcion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
