# Generated by Django 4.2.3 on 2024-07-07 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0007_gato_marcado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gato',
            options={'permissions': [('morir_gato', '')]},
        ),
    ]
