# Generated by Django 4.2.3 on 2024-05-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0008_foto_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gato',
            old_name='foto',
            new_name='retrato',
        ),
        migrations.AddField(
            model_name='foto',
            name='gatos',
            field=models.ManyToManyField(to='gatos.gato'),
        ),
    ]
