# Generated by Django 4.2.3 on 2024-07-08 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gatos.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gatos', '0008_alter_gato_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=gatos.utils.random_choice, max_length=80)),
                ('colonia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendarios_activos', to='gatos.colonia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendarios_activos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
