# Generated by Django 4.2.3 on 2024-07-08 10:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gatos', '0009_accesocalendario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccesoCalendario',
            new_name='CalendarioComidas',
        ),
    ]
