# Generated by Django 4.2.3 on 2024-05-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0009_rename_foto_gato_retrato_foto_gatos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='gatos',
            field=models.ManyToManyField(related_name='fotos', to='gatos.gato'),
        ),
    ]
