# Generated by Django 4.2.3 on 2024-07-08 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0010_rename_accesocalendario_calendariocomidas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendariocomidas',
            old_name='nombre',
            new_name='codigo',
        ),
    ]
