# Generated by Django 4.2.3 on 2024-05-21 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0010_alter_foto_gatos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='colonia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='gatos.colonia'),
        ),
        migrations.AlterField(
            model_name='gato',
            name='colonia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gatos', to='gatos.colonia'),
        ),
    ]
