# Generated by Django 4.2.3 on 2024-05-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0011_alter_foto_colonia_alter_gato_colonia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
