# Generated by Django 4.2.3 on 2024-07-08 11:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gatos', '0011_rename_nombre_calendariocomidas_codigo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CalendarioComidas',
            new_name='CodigoCalendarioComidas',
        ),
    ]
