# Generated by Django 4.2.3 on 2024-05-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0012_alter_foto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='gatos',
            field=models.ManyToManyField(blank=True, related_name='fotos', to='gatos.gato'),
        ),
    ]
