# Generated by Django 4.2.3 on 2024-07-08 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0012_rename_calendariocomidas_codigocalendariocomidas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigocalendariocomidas',
            name='colonia',
        ),
    ]
