# Generated by Django 4.2.3 on 2024-05-23 04:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0013_alter_foto_gatos'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
