# Generated by Django 4.2.23 on 2025-08-12 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gatos', '0013_remove_codigocalendariocomidas_colonia'),
    ]

    operations = [
        migrations.AddField(
            model_name='colonia',
            name='usuarios_autorizados',
            field=models.ManyToManyField(blank=True, help_text='Usuarios que tienen acceso a esta colonia', related_name='colonias_autorizadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
