# Generated by Django 4.2.3 on 2024-05-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0014_foto_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gato',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], default='M', max_length=10),
            preserve_default=False,
        ),
    ]
