# Generated by Django 4.2.23 on 2025-08-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0014_add_usuarios_autorizados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gato',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
