# Generated by Django 4.2.3 on 2024-05-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0018_alter_colonia_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonia',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
