# Generated by Django 4.2.3 on 2024-05-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0019_alter_colonia_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonia',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
