# Generated by Django 4.2.3 on 2024-05-28 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0020_alter_colonia_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
