# Generated by Django 4.2.3 on 2024-06-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0021_foto_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='exif',
            field=models.JSONField(blank=True, default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foto',
            name='miniatura',
            field=models.ImageField(default='', upload_to='miniaturas/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(upload_to='fotos/%Y/%m/%d'),
        ),
    ]
