# Generated by Django 4.2.3 on 2024-06-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0022_foto_exif_foto_miniatura_alter_foto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='exif',
            field=models.JSONField(default={}),
        ),
    ]
