# Generated by Django 4.2.3 on 2024-06-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0023_alter_foto_exif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='exif',
            field=models.JSONField(default=dict),
        ),
    ]
