# Generated by Django 4.2.3 on 2024-06-17 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0024_alter_foto_exif'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatoEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PESADA', 'PESADA'), ('NACIMIENTO', 'Nacimiento'), ('CAPTURA', 'Captura'), ('DEVOLUCION', 'Devolución'), ('MUERTE', 'Muerte'), ('APARICION', 'Aparición'), ('DESAPARICION', 'Desaparición'), ('REAPARICION', 'Reaparición'), ('VACUNACION', 'Vacunación'), ('ENFERMEDAD', 'Enfermedad'), ('CURACION', 'Curación'), ('ESTERILIZACION', 'Esterilización')], max_length=50)),
                ('momento', models.DateTimeField(auto_now=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('observaciones', models.TextField(blank=True)),
                ('gato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='gatos.gato')),
            ],
        ),
        migrations.CreateModel(
            name='ColoniaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FUNDACION', 'Fundación'), ('CLAUSURA', 'Clausura'), ('ABANDONO', 'Abandono')], max_length=50)),
                ('momento', models.DateTimeField(auto_now=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('observaciones', models.TextField(blank=True)),
                ('colonia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='gatos.colonia')),
            ],
        ),
    ]
