# Generated by Django 4.2.3 on 2024-06-21 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gatos', '0025_gatoevent_coloniaevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_captura', models.DateField(auto_now=True)),
                ('fecha_liberacion', models.DateField(blank=True)),
                ('observaciones', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_diagnostico', models.DateField(auto_now=True)),
                ('fecha_curacion', models.DateField(blank=True)),
                ('observaciones', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('OBSERVACION', 'Observación'), ('NACIMIENTO', 'Nacimiento'), ('MUERTE', 'Muerte'), ('APARICION', 'Aparición'), ('DESAPARICION', 'Desaparición'), ('REAPARICION', 'Reaparición')], max_length=50)),
                ('momento', models.DateTimeField(auto_now=True)),
                ('nombre_usuario', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('nombre_usuario', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pesada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('peso', models.DecimalField(decimal_places=1, max_digits=6)),
                ('fecha', models.DateField(auto_now=True)),
                ('observaciones', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='gato',
            name='esterilizacion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='colonia',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='GatoEvent',
        ),
        migrations.AddField(
            model_name='pesada',
            name='gato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesadas', to='gatos.gato'),
        ),
        migrations.AddField(
            model_name='informe',
            name='colonia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatos.colonia'),
        ),
        migrations.AddField(
            model_name='informe',
            name='fotos',
            field=models.ManyToManyField(to='gatos.foto'),
        ),
        migrations.AddField(
            model_name='informe',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evento',
            name='gato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='gatos.gato'),
        ),
        migrations.AddField(
            model_name='evento',
            name='informe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatos.informe'),
        ),
        migrations.AddField(
            model_name='evento',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enfermedad',
            name='gato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfermedades', to='gatos.gato'),
        ),
        migrations.AddField(
            model_name='captura',
            name='gato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capturas', to='gatos.gato'),
        ),
    ]
