# Generated by Django 4.2.3 on 2024-06-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0026_captura_enfermedad_evento_informe_pesada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coloniaevent',
            name='momento',
        ),
        migrations.RemoveField(
            model_name='coloniaevent',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='informe',
        ),
        migrations.RemoveField(
            model_name='informe',
            name='usuario',
        ),
        migrations.AddField(
            model_name='captura',
            name='nombre_usuario',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='captura',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coloniaevent',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coloniaevent',
            name='nombre_usuario',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='enfermedad',
            name='nombre_usuario',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='captura',
            name='fecha_liberacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Pesada',
        ),
    ]
