# Generated by Django 4.2.3 on 2024-06-22 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gatos', '0029_captura_usuario_enfermedad_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(blank=True, default='', max_length=200)),
                ('tipo', models.CharField(choices=[('OBSERVACION', 'Observación'), ('APARICION', 'Aparición'), ('DESAPARICION', 'Desaparición'), ('REAPARICION', 'Reaparición')], max_length=50)),
                ('momento', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('gato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='gatos.gato')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='GatoEvent',
        ),
    ]
