# Generated by Django 4.2.3 on 2024-06-22 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0030_observacion_delete_gatoevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observacion',
            name='tipo',
        ),
        migrations.AddField(
            model_name='observacion',
            name='foto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gatos.foto'),
        ),
        migrations.AlterField(
            model_name='captura',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
