# Generated by Django 4.2.3 on 2024-06-23 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gatos', '0031_remove_observacion_tipo_observacion_foto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVacunacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('efecto', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacunacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efecto', models.DurationField()),
            ],
        ),
        migrations.RemoveField(
            model_name='informe',
            name='colonia',
        ),
        migrations.RemoveField(
            model_name='informe',
            name='fotos',
        ),
        migrations.RemoveField(
            model_name='informe',
            name='momento',
        ),
        migrations.RemoveField(
            model_name='informe',
            name='text',
        ),
        migrations.AddField(
            model_name='captura',
            name='esterilizacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='captura',
            name='sacrificio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foto',
            name='nombre_usuario',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='foto',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='informe',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='informe',
            name='gatos',
            field=models.ManyToManyField(related_name='informes', to='gatos.gato'),
        ),
        migrations.AddField(
            model_name='informe',
            name='texto',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='captura',
            name='fecha_liberacion',
            field=models.DateField(default=None, null=True),
        ),
        migrations.DeleteModel(
            name='Observacion',
        ),
        migrations.AddField(
            model_name='vacunacion',
            name='captura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatos.captura'),
        ),
        migrations.AddField(
            model_name='vacunacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatos.tipovacunacion'),
        ),
    ]
