# Generated by Django 4.2.3 on 2024-06-23 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0032_tipovacunacion_vacunacion_remove_informe_colonia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='colonia',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='gatos.colonia'),
            preserve_default=False,
        ),
    ]
