# Generated by Django 4.2.3 on 2024-06-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0033_informe_colonia'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='titulo',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
