# Generated by Django 4.2.3 on 2024-06-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0034_informe_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfermedad',
            name='fecha_curacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
