# Generated by Django 4.2.3 on 2024-06-24 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0036_vacunacion_nombre_usuario_vacunacion_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacunacion',
            name='captura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to='gatos.captura'),
        ),
        migrations.AlterField(
            model_name='vacunacion',
            name='tipo',
            field=models.CharField(choices=[('DESPARASITADO', 'Desparasitado')], max_length=100),
        ),
        migrations.DeleteModel(
            name='EventoColonia',
        ),
        migrations.DeleteModel(
            name='TipoVacunacion',
        ),
    ]
