# Generated by Django 4.2.3 on 2024-06-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0037_alter_vacunacion_captura_alter_vacunacion_tipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enfermedad',
            options={'verbose_name_plural': 'enfermedades'},
        ),
        migrations.AddField(
            model_name='foto',
            name='fea',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gato',
            name='feo',
            field=models.BooleanField(default=False),
        ),
    ]
