# Generated by Django 4.2.3 on 2024-06-25 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0038_alter_enfermedad_options_foto_fea_gato_feo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacunacion',
            options={'permissions': [('vacunar', '')]},
        ),
    ]
