# Generated by Django 4.2.3 on 2024-06-25 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0039_alter_vacunacion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='captura',
            options={'permissions': [('capturar_gato', ''), ('liberar_gato', '')]},
        ),
        migrations.AlterModelOptions(
            name='vacunacion',
            options={'permissions': [('vacunar_gato', '')]},
        ),
    ]
