# Generated by Django 4.2.3 on 2024-06-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0040_alter_captura_options_alter_vacunacion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='informe',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
