# Generated by Django 4.2.3 on 2024-06-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0041_alter_foto_fecha_alter_informe_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='gato',
            name='nombre_vecino',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gato',
            name='vecino',
            field=models.BooleanField(default=False),
        ),
    ]
