# Generated by Django 4.2.3 on 2024-06-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0042_gato_nombre_vecino_gato_vecino'),
    ]

    operations = [
        migrations.AddField(
            model_name='gato',
            name='desaparecido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gato',
            name='muerto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gato',
            name='sacrificar',
            field=models.BooleanField(default=False),
        ),
    ]
