# Generated by Django 4.2.3 on 2024-06-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0043_gato_desaparecido_gato_muerto_gato_sacrificar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gato',
            name='desaparecido',
        ),
    ]
