# Generated by Django 4.2.3 on 2024-06-27 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0044_remove_gato_desaparecido'),
    ]

    operations = [
        migrations.AddField(
            model_name='colonia',
            name='periodo_activo',
            field=models.DurationField(default=datetime.timedelta(days=120)),
        ),
    ]
