# Generated by Django 4.2.3 on 2024-06-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0045_colonia_periodo_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacunacion',
            options={'permissions': [('vacunar_gato', '')], 'verbose_name_plural': 'vacunaciones'},
        ),
        migrations.AddField(
            model_name='gato',
            name='muerto_fecha',
            field=models.DateField(default=None, null=True),
        ),
    ]
