# Generated by Django 4.2.3 on 2024-06-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0046_alter_vacunacion_options_gato_muerto_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='gato',
            name='fecha_alta',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gato',
            name='esterilizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gato',
            name='muerto_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gato',
            name='nombre_vecino',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
