# Generated by Django 4.2.3 on 2024-06-29 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gatos', '0049_avistamiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avistamiento',
            options={'permissions': [('avistar_gato', '')]},
        ),
        migrations.AlterModelOptions(
            name='planificacioncomida',
            options={'permissions': [('alimentar_gato', '')]},
        ),
        migrations.AlterField(
            model_name='avistamiento',
            name='colonia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avistamientos', to='gatos.colonia'),
        ),
        migrations.CreateModel(
            name='AsignacionComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('colonia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='gatos.colonia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
