# Generated by Django 4.2.3 on 2024-06-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0050_alter_avistamiento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planificacioncomida',
            options={'permissions': [('alimentar_colonia', '')]},
        ),
    ]
