# Generated by Django 4.2.3 on 2024-06-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0051_alter_planificacioncomida_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacioncomida',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='avistamiento',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
