# Generated by Django 4.2.3 on 2024-06-30 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0052_alter_asignacioncomida_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacioncomida',
            name='colonia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comidas', to='gatos.colonia'),
        ),
        migrations.AlterField(
            model_name='avistamiento',
            name='gato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avistamientos', to='gatos.gato'),
        ),
        migrations.DeleteModel(
            name='PlanificacionComida',
        ),
    ]
