# Generated by Django 4.2.3 on 2024-06-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0053_alter_asignacioncomida_colonia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacioncomida',
            name='fecha',
            field=models.DateField(),
        ),
    ]
