# Generated by Django 4.2.3 on 2024-06-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0054_alter_asignacioncomida_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='captura',
            name='sacrificio',
        ),
        migrations.RemoveField(
            model_name='gato',
            name='sacrificar',
        ),
        migrations.AlterField(
            model_name='informe',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
