# Generated by Django 4.2.3 on 2024-07-01 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gatos', '0055_remove_captura_sacrificio_remove_gato_sacrificar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avistamiento',
            name='nombre_usuario',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='avistamiento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
