# Generated by Django 4.2.3 on 2024-07-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0056_avistamiento_nombre_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gato',
            name='estado',
            field=models.CharField(default=[('LIBRE', 'Libre'), ('MARCADO', 'Marcado'), ('CAPTURADO', 'Capturado'), ('DESAPARECIDO', 'Desaparecido'), ('OLVIDADO', 'Olvidado'), ('MUERTO', 'Muerto')], max_length=200),
        ),
    ]
